// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsGUXvcrPWVE13Cu6HWswExHwAUJyfTxA',
    appId: '1:960777458748:web:52cfa81683bf8f40fa1f39',
    messagingSenderId: '960777458748',
    projectId: 'applicationlab-7ec54',
    authDomain: 'applicationlab-7ec54.firebaseapp.com',
    storageBucket: 'applicationlab-7ec54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCadPkJJZSveHS3AzDXBc-7TObZFFVWgvk',
    appId: '1:960777458748:android:b9d6b5b2a67d0db6fa1f39',
    messagingSenderId: '960777458748',
    projectId: 'applicationlab-7ec54',
    storageBucket: 'applicationlab-7ec54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2xA7XwnPUFbPtBGey5cEVDZeM1JjUoC0',
    appId: '1:960777458748:ios:dbbdd49f76843250fa1f39',
    messagingSenderId: '960777458748',
    projectId: 'applicationlab-7ec54',
    storageBucket: 'applicationlab-7ec54.firebasestorage.app',
    iosBundleId: 'com.example.applicationlab',
  );
}
